eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8803
spring:
  application:
    name: zuul-server
zuul:
  routes:
    api-a:
      path: /user/**
      serviceId: user-server
    api-b:
      path: /fm/**
      serviceId: fm-client